### ISSUE TITLE
Warning when building .Net Core 2.2 F# mstets/xunit projects

### ISSUE THREAD

**Issue by seancpeters** [dotnet/test-templates#11]
_From @richaverma1 on September 5, 2018 18:24_

This is blocking 2.2 Preview 2 release -

Repro steps :
1. Create F# .net core mstest/xunit projects and  build
2. dotnet build succeeded with the warning:" A 'Program.fs' file can be automatically generated for F# .NET Core test projects. To fix this warning, either delete the file from the project, or set the <GenerateProgramFile> property to 'false'.”

![fsharpbuilderror](https://user-images.githubusercontent.com/19596695/45112993-082abb00-b0fe-11e8-8b7e-23b1d8a009af.png)
 
Workaround: Edit the .csproj file, set the <GenerateProgramFile> property to 'false'. i.e. :<GenerateProgramFile>false</GenerateProgramFile> 

_Copied from original issue: dotnet/templating#1653_

**Comment by dsplaisted** [comment]
I think this should be fixed in the targets which live in the [Microsoft/vstest](https://github.com/Microsoft/vstest) repo instead of the templates.  Probably the [default value for GenerateProgramFile](https://github.com/Microsoft/vstest/blob/a2b4196f4098978a4c5937ba4f3874a85bf93212/src/package/nuspec/Microsoft.NET.Test.Sdk.targets#L24) should be changed to false if the language is F#.

**Comment by mayankbansal018** [comment]
@dsplaisted , if we make default value to false for F#, then we put onus on users to specify in their csproj, else the test will not be run for those projects.

Further, is this the same case for C# test projects? If not then how do we disable this warning for F#.

**Comment by dsplaisted** [comment]
@mayankbansal018 What's the reason for setting the `OutputType` to `Exe` anyway, which is presumably the reason for GenerateProgramFile?  The [comments in the targets file that set it](https://github.com/Microsoft/vstest/blob/a2b4196f4098978a4c5937ba4f3874a85bf93212/src/package/nuspec/Microsoft.NET.Test.Sdk.targets#L28-L35) link to two old bugs which have been fixed.

Can test projects just use an `OutputType` of `Library` now?  This would especially make things better for F# projects.

**Comment by mayankbansal018** [comment]
@dsplaisted , we set output type to exe for netcore projects, so that a relevant deps file is generated for those project, else it doesn't generate for netcore projects, without which we cannot run the tests..

**Comment by dsplaisted** [comment]
@mayankbansal018 Do you mean the .deps.json file?  Trying it out just now for a .NET Core class library, that file is generated.

If there's some other reason that unit tests as libraries don't work, let us know.  There may be another property you can set to get things working, or we may be able to add more support to the SDK if needed.

**Comment by mayankbansal018** [comment]
@dsplaisted , I tried to run tests via generating test library rather than "exe", & it failed, the reason was because, we failed to find the path of "testhost.dll"(netcore exe which actually runs the test).

We failed to find it because for library "runtimeconfig.dev.json" is not generated, & our currently depends on it to resolve path for "testhost.dll". Please see [this](https://github.com/Microsoft/vstest/blob/a2b4196f4098978a4c5937ba4f3874a85bf93212/src/Microsoft.TestPlatform.TestHostProvider/Hosting/DotnetTestHostManager.cs#L189) 

We can revisit this logic, but I'm skeptical to change it during VS 15.9. I would recommend that for now we remove the Program.fs from f# template, or make some specific change in targets file to not generate main for f# template. Let me know if that is feasible

**Comment by YunWeiaa** [comment]
Repro on CLI/SDK: 2.1.605(runtime- 2.1.12)

**Comment by nohwnd** [comment]
Using the templates that link test.sdk 16.5 I tried it on 2.1, 3.0, 3.1 and 5.0 preview and don't see the behavior in any case. There was no change in this part of templates in the currently shipped version either so I suspect that this is fixed. Let us know if you need more assistance.

**Comment by vdanche** [comment]
Repro on CLI/SDK: 2.1.807(runtime-2.1.19)

**Comment by nohwnd** [comment]
@vdanche are you able to repro this in any of the recent versions of sdk? What is the Test.SDK nuget package you are referencing from the project?

The warning is coming from vstest, from here, this will get added when you add Microsoft.NET.Test.Sdk: 
https://github.com/microsoft/vstest/blob/master/src/package/nuspec/netcoreapp/Microsoft.NET.Test.Sdk.targets#L46

**Comment by vdanche** [comment]
@nohwnd  also repro on CLI/SDK: 2.1.810(runtime- 2.1.22) when testing September Update. The contents show as below in *.fsproj of xunit.
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Tests.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.9.0" />
    <PackageReference Include="xunit" Version="2.4.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.0" />
  </ItemGroup>

</Project>


Note: The warning will disappear after using below workaround.
Add to the project file.
<GenerateProgramFile>false</GenerateProgramFile>

**Comment by Evangelink** [comment]
Just checked and I no longer see warnings with new versions. I'll move forward by closing this issue but please ping me if you are still seeing the error.
